### ISSUE TITLE
BroadcastBuf problem in if-then-else branch; Race condition? "cannot push port twice"

### ISSUE THREAD

**Issue by Sciss** [Sciss/FScape-next#37]
In GitLab by @Sciss on Mar 11, 2019, 24:00

With this example:

```
val levels    = Seq[GE](0.0, -1.0, 1.0, 0.1)
val lengths   = Seq       (100, 200, 50)
val lengthsG  = lengths.map(x => x: GE)
val shapes    = Seq[GE]    (1,   3,   2)    // lin, sine, exp

val env       = DEnvGen(
  levels  = levels  .reduce(_ ++ _),
  lengths = lengthsG.reduce(_ ++ _),
  shapes  = shapes  .reduce(_ ++ _))

Length(env).poll(0, "length")

Plot1D(env, size = lengths.sum, label = "env")```
```

Sometimes plot does not open, sometimes this error is thrown:

```
[ERROR] [03/10/2019 23:56:59.645] [fscape-akka.actor.default-dispatcher-6] [akka://fscape/system/StreamSupervisor-0/flow-17-0-singleSource] Error in stage [BroadcastBuf@5d256b6b]: Cannot push port (BroadcastBuf.out0(641860441)) twice, or before it being pulled
java.lang.IllegalArgumentException: Cannot push port (BroadcastBuf.out0(641860441)) twice, or before it being pulled
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:570)
	at de.sciss.fscape.stream.BroadcastBuf$Logic.onPush(BroadcastBuf.scala:87)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:504)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:374)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Mar 11, 2019, 24:04

Reproducible: `BloodyTest`:

```scala
    val sz = 17000

    val in        = SinOsc(freqN = 1.0/16 /* 4410/sr */, phase = 0 /* math.Pi/2 */).take(sz)
    val max       = RunningMax(in).last
    val buf       = BufferDisk(in)
    val sig       = buf * max
    Length(sig).poll(0, "len")
```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Mar 11, 2019, 24:14

Ok, this was due to the fact that the original version of `BroadcastBuf` did _not_ pull its input eagerly.

**Comment by Sciss** [comment]
In GitLab by @Sciss on Mar 11, 2019, 01:11

mentioned in commit d32c452f2fc6f90bba1580d28f4f791cad32093b

**Comment by Sciss** [comment]
In GitLab by @Sciss on Mar 11, 2019, 01:12

closed
