### ISSUE TITLE
ReduceWindow - index out of bounds

### ISSUE THREAD

**Issue by Sciss** [Sciss/FScape-next#58]
In GitLab by @Sciss on Feb 3, 2020, 15:46

E.g. input length is 7132672, add a `val slid = Sliding(in, 2048, 512)`, then a `ReduceWindow.max(slid, 2048)` eventually  throws

```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2048
	at java.base/java.util.Arrays.rangeCheck(Arrays.java:123)
	at java.base/java.util.Arrays.fill(Arrays.java:3587)
	at de.sciss.fscape.stream.StreamIn$DoubleType$.clear(StreamIn.scala:68)
	at de.sciss.fscape.stream.StreamIn$DoubleType$.clear(StreamIn.scala:53)
	at de.sciss.fscape.stream.impl.DemandWindowedLogic.clearInputTail(DemandWindowedLogic.scala:77)
	at de.sciss.fscape.stream.impl.DemandWindowedLogic.clearInputTail$(DemandWindowedLogic.scala:76)
	at de.sciss.fscape.stream.ReduceWindow$Logic.clearInputTail(ReduceWindow.scala:45)
	at de.sciss.fscape.stream.impl.DemandWindowedLogic.process(DemandWindowedLogic.scala:243)
	at de.sciss.fscape.stream.impl.DemandWindowedLogic.process$(DemandWindowedLogic.scala:182)
	at de.sciss.fscape.stream.ReduceWindow$Logic.process(ReduceWindow.scala:45)
	at de.sciss.fscape.stream.impl.DemandWindowedLogic$_InHandlerImpl.onUpstreamFinish(DemandWindowedLogic.scala:140)
```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 3, 2020, 15:48

changed the description

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 3, 2020, 15:52

need to override `clearInputTail` because we do not allocate a win buffer here.

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 3, 2020, 19:07

mentioned in commit 0e2045242dcda9ff79f6c5694d0147ca5f46872d

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 3, 2020, 19:13

closed
