### ISSUE TITLE
Slices: NPE with certain spans

### ISSUE THREAD

**Issue by Sciss** [Sciss/FScape-next#59]
In GitLab by @Sciss on Feb 16, 2020, 16:30

Might be that we overshoot the input size due to floating point noise?

```scala
      val chunkSize     = 4096  // 65536
      val numChunks     = 128   // 176
      val numFramesIn   = numChunks * chunkSize
      val in0           = DC(0.0).take(numFramesIn)
      val sliceIndices  = Seq[GE](0, numChunks - 1)
      val spanStart     = sliceIndices.reduce(_ ++ _) * chunkSize
      val spanStop      = spanStart + chunkSize
      val spans         = spanStart zip spanStop

      val slices = Slices(in0, spans)
      Length(slices).poll(0, "length")
```

```
java.lang.NullPointerException
	at de.sciss.fscape.stream.Slices$Logic.de$sciss$fscape$stream$Slices$Logic$$process(Slices.scala:196)
	at de.sciss.fscape.stream.Slices$Logic.onPull(Slices.scala:235)
```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 16, 2020, 16:32

changed the description

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 16, 2020, 17:19

mentioned in commit 30523a0d177a82ad987e9fa2e0656665a2c74b58

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 20, 2020, 20:35

closed
